export const dynamic = 'force-dynamic'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import PrintControls from '@/components/PrintControls'

const COOKIE = 'sms_auth'
const PIN    = process.env.ACCESS_PIN || '1234'

export default async function PrintCustomersPage({ searchParams }) {
  const token = (await cookies()).get(COOKIE)?.value
  if (token !== PIN) redirect('/login')

  const sp = await searchParams
  const q  = sp?.q || ''

  const where = q
    ? { OR: [
        { customerName: { contains: q } },
        { phoneNumber:  { contains: q } },
        { ntn:          { contains: q } },
      ] }
    : {}

  const customers = await prisma.customer.findMany({
    where,
    orderBy: { customerName: 'asc' },
  })

  const printDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  return (
    <>
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; }
          table { page-break-inside: auto; }
          tr    { page-break-inside: avoid; }
        }
        * { box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 12px; color: #1a1a1a; background: #fff; margin: 0; padding: 0; }
      `}</style>

      {/* Screen controls */}
      <PrintControls />

      {/* Document */}
      <div style={{ maxWidth: 960, margin: '32px auto', padding: '40px 48px', background: '#fff', boxShadow: '0 2px 24px rgba(0,0,0,.08)' }}>

        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32 }}>
          <div>
            <div style={{ fontSize: 26, fontWeight: 800, color: '#1a1a1a', letterSpacing: -0.5 }}>CUSTOMERS REPORT</div>
            <div style={{ fontSize: 13, color: '#6b7280', marginTop: 4 }}>Stock Management System</div>
            {q && <div style={{ fontSize: 12, color: '#9ca3af', marginTop: 2 }}>Filter: {q}</div>}
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 12, color: '#9ca3af' }}>{printDate}</div>
            <div style={{ fontSize: 13, color: '#7c3aed', fontWeight: 700, marginTop: 4 }}>{customers.length} customer(s)</div>
          </div>
        </div>

        <div style={{ borderTop: '2px solid #7c3aed', marginBottom: 20 }} />

        {/* Customers table */}
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#f8f5ff' }}>
              {['Name', 'Phone', 'NTN', 'GST No.', 'Filer', 'Address'].map((h, i) => (
                <th key={h} style={{
                  textAlign: 'left',
                  padding: '9px 10px',
                  fontSize: 10,
                  fontWeight: 700,
                  textTransform: 'uppercase',
                  letterSpacing: 1,
                  color: '#7c3aed',
                  borderBottom: '2px solid #e5e7eb',
                  whiteSpace: 'nowrap',
                }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {customers.length === 0 && (
              <tr><td colSpan={6} style={{ padding: '24px', textAlign: 'center', color: '#9ca3af', fontStyle: 'italic' }}>No customers found</td></tr>
            )}
            {customers.map((row, idx) => (
              <tr key={row.customerId} style={{ borderBottom: '1px solid #f3f4f6', background: idx % 2 === 1 ? '#fafafa' : '#fff' }}>
                <td style={{ padding: '8px 10px', fontWeight: 600, color: '#1a1a1a' }}>{row.customerName}</td>
                <td style={{ padding: '8px 10px', fontFamily: 'monospace', fontSize: 11, color: '#374151' }}>{row.phoneNumber || '—'}</td>
                <td style={{ padding: '8px 10px', fontFamily: 'monospace', fontSize: 11, color: '#374151' }}>{row.ntn || '—'}</td>
                <td style={{ padding: '8px 10px', fontFamily: 'monospace', fontSize: 11, color: '#374151' }}>{row.gstNumber || '—'}</td>
                <td style={{ padding: '8px 10px', fontSize: 11, color: '#374151' }}>{row.filerStatus || '—'}</td>
                <td style={{ padding: '8px 10px', fontSize: 11, color: '#6b7280', maxWidth: 180 }}>{row.address || '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Footer */}
        <div style={{ borderTop: '1px solid #e5e7eb', marginTop: 32, paddingTop: 16, display: 'flex', justifyContent: 'space-between', fontSize: 11, color: '#9ca3af' }}>
          <span>Generated by Stock Management System · {printDate}</span>
          <span>{customers.length} record(s) printed</span>
        </div>
      </div>
    </>
  )
}
